gen3:
  profile: local
  project_id: fhir_aggregator-cda
  version: null
log:
  format: '[%(asctime)s] [%(levelname)s] %(name)s %(message)s'
  level: INFO
output:
  format: yaml
work_dir: .g3t/work
state_dir: .g3t/state
